name: Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17

    - name: Build with Maven
      run: mvn -B clean package -DskipTests
      
#       build project and run all tests & checks
    - name: Maven Verify
      run: mvn -B clean verify

#       Upload code coverage report to Codecov
    - name: Test Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}    
